#!/usr/bin/env node
// Renders assets/social-preview.html to assets/social-preview.png at 1280×640 — the
// card every link to the site unfurls into, and the image the og:image and twitter:image
// tags in site/build.mjs have been naming since before it existed (TH-14).
//
//   node scripts/social.mjs                  assets/social-preview.png
//   node scripts/social.mjs --out /tmp/x.png
//   CHROME=/path/to/chrome node scripts/social.mjs
//
// Headless Chrome and nothing else: no dependency enters package.json for an image
// regenerated by hand a few times a year. The browser is found, not installed — if it is
// not on this machine the script says so and exits non-zero rather than shipping a stale
// card or a silently missing one.
//
// The card's HTML references assets/logo.svg by path, so the mark on it is the one file
// the favicon and the README also use. Change the logo and the card follows.

import { spawn } from 'node:child_process'
import { existsSync, mkdtempSync, rmSync, statSync, unlinkSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const argv = process.argv.slice(2)
const outArg = argv.indexOf('--out')
const OUT = resolve(ROOT, outArg >= 0 ? argv[outArg + 1] : 'assets/social-preview.png')
const SOURCE = join(ROOT, 'assets', 'social-preview.html')
const WIDTH = 1280
const HEIGHT = 640

const CANDIDATES = [
  process.env.CHROME,
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
  '/usr/bin/google-chrome',
  '/usr/bin/chromium',
  '/usr/bin/chromium-browser',
  '/usr/bin/microsoft-edge',
].filter(Boolean)

const chrome = CANDIDATES.find((p) => existsSync(p))
if (!chrome) {
  console.error('no Chrome, Chromium or Edge found — set CHROME=/path/to/the/binary')
  console.error(`looked in:\n  ${CANDIDATES.join('\n  ')}`)
  process.exit(1)
}
if (!existsSync(SOURCE)) {
  console.error(`missing ${SOURCE}`)
  process.exit(1)
}

// A throwaway profile: rendering a card must not touch, or be touched by, the browser
// profile the person is actually using.
const profile = mkdtempSync(join(tmpdir(), 'trimhook-shot-'))

// Chrome writes the screenshot and then does not exit — measured on 153.0.8010.48,
// macOS, in both `--headless` and `--headless=new`. Waiting for the process is waiting
// for ever, so this waits for the *file* instead: it appears, its size stops changing,
// and the browser is then stopped. Detached, so the kill reaches the whole process group
// rather than a parent whose children keep the profile directory busy.
if (existsSync(OUT)) unlinkSync(OUT) // never mistake yesterday's card for today's
const child = spawn(
  chrome,
  [
    '--headless',
    '--disable-gpu',
    '--hide-scrollbars',
    '--no-first-run',
    '--no-default-browser-check',
    '--disable-extensions',
    '--disable-background-networking',
    '--force-device-scale-factor=2', // a retina card; feeds downscale it, never up
    `--user-data-dir=${profile}`,
    `--window-size=${WIDTH},${HEIGHT}`,
    `--screenshot=${OUT}`,
    `file://${SOURCE}`,
  ],
  { stdio: ['ignore', 'ignore', 'pipe'], detached: true },
)
let stderr = ''
child.stderr.on('data', (d) => {
  stderr += d
})

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const deadline = Date.now() + 45_000
let last = -1
let done = false
while (Date.now() < deadline) {
  await sleep(200)
  if (existsSync(OUT)) {
    const size = statSync(OUT).size
    if (size > 0 && size === last) {
      done = true
      break
    }
    last = size
  } else if (child.exitCode !== null) break
}
try {
  process.kill(-child.pid, 'SIGKILL')
} catch {
  // already gone
}
rmSync(profile, { recursive: true, force: true })

if (!done) {
  console.error(`no screenshot after 45 s${stderr.trim() ? `\n${stderr.trim()}` : ''}`)
  process.exit(1)
}
console.log(`wrote ${OUT} — ${(statSync(OUT).size / 1024).toFixed(1)} kB, ${WIDTH}×${HEIGHT} at 2×`)
